//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeskQuadra.UI.Wpf.Properties
{
    using System;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///   pt-BR default, único idioma.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings
    {
        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Strings()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeskQuadra.UI.Wpf.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        public static string TrayTooltip => ResourceManager.GetString("TrayTooltip", resourceCulture);

        public static string TrayShowHiddenQuadras => ResourceManager.GetString("TrayShowHiddenQuadras", resourceCulture);

        public static string TrayShowAll => ResourceManager.GetString("TrayShowAll", resourceCulture);

        public static string TrayLockAllQuadras => ResourceManager.GetString("TrayLockAllQuadras", resourceCulture);

        public static string TrayExit => ResourceManager.GetString("TrayExit", resourceCulture);

        public static string TrayNoHiddenQuadras => ResourceManager.GetString("TrayNoHiddenQuadras", resourceCulture);

        public static string HangTestMenuLabel => ResourceManager.GetString("HangTestMenuLabel", resourceCulture);

        public static string HangTestConfirmMessage => ResourceManager.GetString("HangTestConfirmMessage", resourceCulture);

        public static string HangTestConfirmTitle => ResourceManager.GetString("HangTestConfirmTitle", resourceCulture);

        public static string CreationMenuCreateQuadraHere => ResourceManager.GetString("CreationMenuCreateQuadraHere", resourceCulture);

        public static string CreationMenuCancelAndShowWindowsMenu => ResourceManager.GetString("CreationMenuCancelAndShowWindowsMenu", resourceCulture);

        public static string QuadraDefaultTitleFormat => ResourceManager.GetString("QuadraDefaultTitleFormat", resourceCulture);

        public static string QuadraMenu_Rescan => ResourceManager.GetString("QuadraMenu_Rescan", resourceCulture);

        public static string QuadraMenu_SortBy => ResourceManager.GetString("QuadraMenu_SortBy", resourceCulture);

        public static string QuadraMenu_SortName => ResourceManager.GetString("QuadraMenu_SortName", resourceCulture);

        public static string QuadraMenu_SortType => ResourceManager.GetString("QuadraMenu_SortType", resourceCulture);

        public static string QuadraMenu_SortDate => ResourceManager.GetString("QuadraMenu_SortDate", resourceCulture);

        public static string QuadraMenu_SortManual => ResourceManager.GetString("QuadraMenu_SortManual", resourceCulture);

        public static string QuadraMenu_NewQuadra => ResourceManager.GetString("QuadraMenu_NewQuadra", resourceCulture);

        public static string QuadraMenu_LockQuadra => ResourceManager.GetString("QuadraMenu_LockQuadra", resourceCulture);

        public static string QuadraMenu_CloseQuadra => ResourceManager.GetString("QuadraMenu_CloseQuadra", resourceCulture);

        public static string Quadra_LockedTooltip => ResourceManager.GetString("Quadra_LockedTooltip", resourceCulture);

        public static string Quadra_CollapseTooltip => ResourceManager.GetString("Quadra_CollapseTooltip", resourceCulture);

        public static string Quadra_ExpandTooltip => ResourceManager.GetString("Quadra_ExpandTooltip", resourceCulture);

        public static string Quadra_AddTooltip => ResourceManager.GetString("Quadra_AddTooltip", resourceCulture);

        public static string Quadra_CloseTooltip => ResourceManager.GetString("Quadra_CloseTooltip", resourceCulture);

        public static string Quadra_EmptyMessage => ResourceManager.GetString("Quadra_EmptyMessage", resourceCulture);

        public static string ItemMenu_Open => ResourceManager.GetString("ItemMenu_Open", resourceCulture);

        public static string ItemMenu_OpenLocation => ResourceManager.GetString("ItemMenu_OpenLocation", resourceCulture);

        public static string ItemMenu_Remove => ResourceManager.GetString("ItemMenu_Remove", resourceCulture);

        public static string ItemMenu_Move => ResourceManager.GetString("ItemMenu_Move", resourceCulture);

        public static string Dialog_CloseTitle => ResourceManager.GetString("Dialog_CloseTitle", resourceCulture);

        public static string Dialog_CloseMessageFormat => ResourceManager.GetString("Dialog_CloseMessageFormat", resourceCulture);

        public static string Dialog_Hide => ResourceManager.GetString("Dialog_Hide", resourceCulture);

        public static string Dialog_Delete => ResourceManager.GetString("Dialog_Delete", resourceCulture);

        public static string Dialog_Cancel => ResourceManager.GetString("Dialog_Cancel", resourceCulture);

        public static string Dialog_DeleteDefaultTitle => ResourceManager.GetString("Dialog_DeleteDefaultTitle", resourceCulture);

        public static string Dialog_DeleteDefaultMessage => ResourceManager.GetString("Dialog_DeleteDefaultMessage", resourceCulture);

        public static string Dialog_AddFilesTitle => ResourceManager.GetString("Dialog_AddFilesTitle", resourceCulture);

        public static string FileCopySuffix => ResourceManager.GetString("FileCopySuffix", resourceCulture);

        public static string FileCopySuffixIndexedFormat => ResourceManager.GetString("FileCopySuffixIndexedFormat", resourceCulture);

        public static string Selection_NewQuadra => ResourceManager.GetString("Selection_NewQuadra", resourceCulture);

        public static string TraySettings => ResourceManager.GetString("TraySettings", resourceCulture);

        public static string SettingsTitle => ResourceManager.GetString("SettingsTitle", resourceCulture);

        public static string SettingsStartup => ResourceManager.GetString("SettingsStartup", resourceCulture);

        public static string SettingsAppearanceTitle => ResourceManager.GetString("SettingsAppearanceTitle", resourceCulture);

        public static string SettingsDensityAuto => ResourceManager.GetString("SettingsDensityAuto", resourceCulture);

        public static string SettingsDensityNormal => ResourceManager.GetString("SettingsDensityNormal", resourceCulture);

        public static string SettingsDensityTouch => ResourceManager.GetString("SettingsDensityTouch", resourceCulture);

        public static string Dialog_RecoveryTitle => ResourceManager.GetString("Dialog_RecoveryTitle", resourceCulture);

        public static string Dialog_RecoveryMessage => ResourceManager.GetString("Dialog_RecoveryMessage", resourceCulture);

        public static string Dialog_RestoreRecent => ResourceManager.GetString("Dialog_RestoreRecent", resourceCulture);

        public static string Dialog_KeepPrevious => ResourceManager.GetString("Dialog_KeepPrevious", resourceCulture);
    }
}
